name: yes_or_no
description: A futuristic 1v1 deduction game where players compete to identify a secret word through strategic yes/no questions.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  
  # UI & Design
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  
  # Utilities
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
  
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: fonts/SpaceGrotesk-Bold.ttf
          weight: 700
    
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Bold.ttf
          weight: 700
