// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJGxJt7TkXIAY1jDXLDZRUf4EwR1Ys3ZU',
    appId: '1:612385880653:web:1def8a195087715abffa04',
    messagingSenderId: '612385880653',
    projectId: 'yesorno-85a02',
    authDomain: 'yesorno-85a02.firebaseapp.com',
    storageBucket: 'yesorno-85a02.firebasestorage.app',
    measurementId: 'G-JRXFSCY7M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAjHVrxzbJ8e6ot-7nURjMwLN3kjK5wi8',
    appId: '1:612385880653:android:8374b52c803282fbbffa04',
    messagingSenderId: '612385880653',
    projectId: 'yesorno-85a02',
    storageBucket: 'yesorno-85a02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnqT3dhnOzcb2cyJkjs5sRFwHjHu72Qfo',
    appId: '1:612385880653:ios:6e29d6fcb87b62c2bffa04',
    messagingSenderId: '612385880653',
    projectId: 'yesorno-85a02',
    storageBucket: 'yesorno-85a02.firebasestorage.app',
    iosBundleId: 'com.example.yesOrNo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnqT3dhnOzcb2cyJkjs5sRFwHjHu72Qfo',
    appId: '1:612385880653:ios:6e29d6fcb87b62c2bffa04',
    messagingSenderId: '612385880653',
    projectId: 'yesorno-85a02',
    storageBucket: 'yesorno-85a02.firebasestorage.app',
    iosBundleId: 'com.example.yesOrNo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJGxJt7TkXIAY1jDXLDZRUf4EwR1Ys3ZU',
    appId: '1:612385880653:web:48105d84f96d47adbffa04',
    messagingSenderId: '612385880653',
    projectId: 'yesorno-85a02',
    authDomain: 'yesorno-85a02.firebaseapp.com',
    storageBucket: 'yesorno-85a02.firebasestorage.app',
    measurementId: 'G-L4MJJD6M5L',
  );
}
